#!/usr/bin/env ruby

require_relative '../lib/kumo_docker_cloud'

def run_command(cmd)
  puts cmd
  puts `#{cmd}`
  raise "non zero exit code" if $?.exitstatus != 0
end

tag = KumoDockerCloud::VERSION

run_command "git tag #{tag}"
run_command "git push origin #{tag}"
